version: '2'
services:
  item-app:
    image: kamaxman/item-app:v1
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - item-db 
  item-db:
    image: mongo:3
    restart: always
    volumes:
      - app-db:/data/db

volumes:
  app-db: